### PR TITLE
Generic logging adapter introduced

### PR DESCRIPTION
**Pull request by JurajBurian**
Would be nice, to have possibility to use an Logging trait outside of Actor in Akka application. So there is a simple solution.

### CODE REVIEW

**Comment by JurajBurian** [comment]
The implementation as is is wrong. Actor system is created in initialization phase. Exists there a way how to do initialization properly ?

**Comment by hseeberger** [comment]
@JurajBurian as you have noticed this won't work. The scope of this project is to provide actor logging, hence I'm closing this.

**Comment by JurajBurian** [comment]
May be there is not general solution of the problem, but for example for play we can do next: 
```:Scala
trait PlayLogging {
  import akka.event.Logging
  import play.api.Play.current

  lazy val log =  LoggingAdapter(Logging(Akka.system, getClass))
}
```
The question is,  do you want support logging in play (thru Akka logging) ? It brings new (provided) dependency to your project.

**Comment by hseeberger** [comment]
@JurajBurian, there are easier ways to use Macros for logging, e.g. ScalaLogging, than trying to tweak this project.

**Pull request closed without merging**
